[project]
name = "goit-pythonweb-hw-04"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofile",
    "aiopath",
    "aioshutil",
    "anyio",
    "asyncio",
    "caio",
    "idna",
    "sniffio"
]
